# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'MeMeDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
	use_modular_headers!

  # Pods for MeMeBaseKitDemo

  pod 'MeMeTwitter', :path => '../'

end
